/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import controller.Concesionario;
import static controller.Concesionario.vehiculos;
import model.Vehiculo;

/**
 *
 * @author ignac
 */
public class insertarView extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(insertarView.class.getName());

    /**
     * Creates new form insertarView
     */
    public insertarView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        InsertarVehiculoBOTON_ENVIAR = new javax.swing.JButton();
        matriculaVal = new javax.swing.JTextField();
        marcaVal = new javax.swing.JTextField();
        modeloVal = new javax.swing.JTextField();
        precioVal = new javax.swing.JTextField();
        tipoVal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Insertar Vehiculo");

        jLabel2.setText("Matricula");

        jLabel3.setText("Marca");

        jLabel4.setText("Modelo");

        jLabel5.setText("Precio");

        jLabel6.setText("Tipo");

        InsertarVehiculoBOTON_ENVIAR.setText("Insertar");
        InsertarVehiculoBOTON_ENVIAR.addActionListener(this::InsertarVehiculoBOTON_ENVIARActionPerformed);

        matriculaVal.addActionListener(this::matriculaValActionPerformed);

        marcaVal.addActionListener(this::marcaValActionPerformed);

        modeloVal.addActionListener(this::modeloValActionPerformed);

        precioVal.addActionListener(this::precioValActionPerformed);

        tipoVal.addActionListener(this::tipoValActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(InsertarVehiculoBOTON_ENVIAR, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(matriculaVal)
                                .addComponent(marcaVal)
                                .addComponent(modeloVal)
                                .addComponent(precioVal, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                                .addComponent(tipoVal))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(matriculaVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(marcaVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modeloVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precioVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(tipoVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(InsertarVehiculoBOTON_ENVIAR)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void marcaValActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marcaValActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marcaValActionPerformed

    private void InsertarVehiculoBOTON_ENVIARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertarVehiculoBOTON_ENVIARActionPerformed
        // TODO add your handling code here: 
        
        
        String matricula = matriculaVal.getText().trim().toUpperCase();
        String marca = marcaVal.getText().trim();
        String modelo = modeloVal.getText().trim();
        String precioString = precioVal.getText().trim();
        String tipo = tipoVal.getText().trim();

        // Validar campos vacíos
        if (matricula.isEmpty() || marca.isEmpty() || modelo.isEmpty()|| precioString.isEmpty() || tipo.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Todos los campos son obligatorios.",
                    "Error",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // ahora convierto el precio a double
        double precio;
        try {
            precio = Double.parseDouble(precioString);
        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "El precio debe ser un número.",
                    "Error",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            Vehiculo v = new Vehiculo(matricula, marca, modelo, precio, tipo);
            Concesionario.insertarVehiculo(v); 
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Vehículo insertado correctamente.",
                    "BIEN",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
            dispose();
        } catch (IllegalArgumentException ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    ex.getMessage(),
                    " Duplicado",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_InsertarVehiculoBOTON_ENVIARActionPerformed

    private void matriculaValActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matriculaValActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matriculaValActionPerformed

    private void modeloValActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modeloValActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modeloValActionPerformed

    private void precioValActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioValActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precioValActionPerformed

    private void tipoValActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoValActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoValActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
             */
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
                logger.log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>

            /* Create and display the dialog */
            java.awt.EventQueue.invokeLater(new Runnable() {
                @Override
                public void run() {
                    insertarView dialog = new insertarView(new javax.swing.JFrame(), true);
                    dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                        @Override
                        public void windowClosing(java.awt.event.WindowEvent e) {
                            System.exit(0);
                        }
                    });
                    dialog.setVisible(true);
                }
            });
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton InsertarVehiculoBOTON_ENVIAR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField marcaVal;
    private javax.swing.JTextField matriculaVal;
    private javax.swing.JTextField modeloVal;
    private javax.swing.JTextField precioVal;
    private javax.swing.JTextField tipoVal;
    // End of variables declaration//GEN-END:variables
}
