/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

/**
 *
 * @author ignac
 */
public class modificarView extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(modificarView.class.getName());

    /**
     * Creates new form modificarView
     */
    public modificarView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cargarVehiculos();
        cargarAtributos();
    }

//para mostrar los vehiculos de la bbdd al combobox
    private void cargarVehiculos() {
        vehiculosPARAMODIFICAA.removeAllItems();
        java.util.ArrayList<model.Vehiculo> lista = controller.Concesionario.listarVehiculos();
        if (lista == null || lista.isEmpty()) {
            vehiculosPARAMODIFICAA.addItem("-- Sin vehículos --");
        } else {
            for (model.Vehiculo v : lista) {
                vehiculosPARAMODIFICAA.addItem(v.getMatricula());
            }
        }
    }

 // para  mostrar atributos en el combobox
    private void cargarAtributos() {
        atributosVehiculosaMODIFICAR.removeAllItems();
        atributosVehiculosaMODIFICAR.addItem("marca");
        atributosVehiculosaMODIFICAR.addItem("modelo");
        atributosVehiculosaMODIFICAR.addItem("precio");
        atributosVehiculosaMODIFICAR.addItem("tipo");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        vehiculosPARAMODIFICAA = new javax.swing.JComboBox<>();
        atributosVehiculosaMODIFICAR = new javax.swing.JComboBox<>();
        modificarBOTON = new javax.swing.JButton();
        IntroducirDATOS = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Modificar Vehiculo");

        vehiculosPARAMODIFICAA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        atributosVehiculosaMODIFICAR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        modificarBOTON.setText("MODIFICAR");
        modificarBOTON.addActionListener(this::modificarBOTONActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(modificarBOTON)))
                .addContainerGap(164, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(IntroducirDATOS, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(vehiculosPARAMODIFICAA, 0, 276, Short.MAX_VALUE)
                        .addComponent(atributosVehiculosaMODIFICAR, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(vehiculosPARAMODIFICAA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(atributosVehiculosaMODIFICAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(IntroducirDATOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(modificarBOTON)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modificarBOTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarBOTONActionPerformed


        String matricula = (String) vehiculosPARAMODIFICAA.getSelectedItem();

        String atributo = (String) atributosVehiculosaMODIFICAR.getSelectedItem();


        String nuevoValor = IntroducirDATOS.getText().trim();


        if (matricula == null || matricula.equals("BBDD VACIA")) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "No hay vehículos disponibles para modificar.",
                    "Sin vehículos",
                    javax.swing.JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        // Validación: campo de nuevo valor vacío
        if (nuevoValor.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Por favor, introduce el nuevo valor en el campo de texto.",
                    "Campo vacío",
                    javax.swing.JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        // Llamar al controlador para modificar el vehículo
        try {
            controller.Concesionario.modificarVehiculo(matricula, atributo, nuevoValor);
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Vehículo con matrícula " + matricula + "modificado correctamente"
                    + "Atributo: " + atributo + " ha cambiado ha: " + nuevoValor,
                    "Modificado",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE
            );
            IntroducirDATOS.setText("");
        } catch (IllegalArgumentException e) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Error al modificar: " + e.getMessage(),
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );
        }

    }//GEN-LAST:event_modificarBOTONActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                modificarView dialog = new modificarView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IntroducirDATOS;
    private javax.swing.JComboBox<String> atributosVehiculosaMODIFICAR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton modificarBOTON;
    private javax.swing.JComboBox<String> vehiculosPARAMODIFICAA;
    // End of variables declaration//GEN-END:variables
}
