/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.Concesionario;
import java.io.IOException;
import java.util.ArrayList;
import persistencia.Fichero;
import static persistencia.Fichero.nombreArchivo;

/**
 *
 * @author ignac
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());
    private Fichero fichero;
    private Concesionario concesionario;

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        Fichero fichero = new Fichero(nombreArchivo);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        insertarBOTON = new javax.swing.JButton();
        buscarBOTON = new javax.swing.JButton();
        eliminarBOTON = new javax.swing.JButton();
        listarBOTON = new javax.swing.JButton();
        ContarVehiculos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Menu");

        insertarBOTON.setText("Insertar Vehiculo");
        insertarBOTON.addActionListener(this::insertarBOTONActionPerformed);

        buscarBOTON.setText("Buscar Vehiculo");
        buscarBOTON.addActionListener(this::buscarBOTONActionPerformed);

        eliminarBOTON.setText("Eliminar Vehiculo");
        eliminarBOTON.addActionListener(this::eliminarBOTONActionPerformed);

        listarBOTON.setText("Listar Vehiculos");
        listarBOTON.addActionListener(this::listarBOTONActionPerformed);

        ContarVehiculos.setText("Contar Vehiculos");
        ContarVehiculos.addActionListener(this::ContarVehiculosActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(insertarBOTON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eliminarBOTON, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buscarBOTON, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listarBOTON, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ContarVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(insertarBOTON)
                .addGap(27, 27, 27)
                .addComponent(buscarBOTON)
                .addGap(18, 18, 18)
                .addComponent(eliminarBOTON)
                .addGap(28, 28, 28)
                .addComponent(listarBOTON)
                .addGap(32, 32, 32)
                .addComponent(ContarVehiculos)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarBOTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarBOTONActionPerformed
        // TODO add your handling code here:
        buscarView ventana = new buscarView(this, true);
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);


    }//GEN-LAST:event_buscarBOTONActionPerformed

    private void insertarBOTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertarBOTONActionPerformed
        // TODO add your handling code here:
        insertarView ventana = new insertarView(this, true);
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);


    }//GEN-LAST:event_insertarBOTONActionPerformed

    private void eliminarBOTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarBOTONActionPerformed
        // TODO add your handling code here:
        eliminarView ventana = new eliminarView(this, true);
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);

    }//GEN-LAST:event_eliminarBOTONActionPerformed

    private void listarBOTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarBOTONActionPerformed
        // TODO add your handling code here:
        listarView ventana = new listarView(this, true);
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);


    }//GEN-LAST:event_listarBOTONActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        fichero = new Fichero("archivo.txt");
        concesionario = new Concesionario();
        try {
            concesionario.vehiculos = fichero.cargar();

            //cuando la ventana se abre se crea el archivo si no esta y se carga todo al arraylist
        } catch (IOException ex) {
            System.getLogger(VentanaPrincipal.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }

    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            // TODO add your handling code here:

            //cuando la ventana principal se cierra se guarda todo
            fichero.guardar(concesionario.vehiculos);
        } catch (IOException ex) {
            System.getLogger(VentanaPrincipal.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_formWindowClosing

    private void ContarVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContarVehiculosActionPerformed
        // TODO add your handling code here:
        contarVehiculosView ventana = new contarVehiculosView(this, true);
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
    }//GEN-LAST:event_ContarVehiculosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ContarVehiculos;
    private javax.swing.JButton buscarBOTON;
    private javax.swing.JButton eliminarBOTON;
    private javax.swing.JButton insertarBOTON;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton listarBOTON;
    // End of variables declaration//GEN-END:variables
}
